export const phase40AcceptanceRegistry = {
  T: ['A->B:P1', 'A->B:P2', 'A->B:P3', 'A->B:P4', 'B->A:P1', 'B->A:P2', 'B->A:P3', 'B->A:P4'],
  R: [
    'TEACHER:request',
    'TEACHER:process',
    'TEACHER:status',
    'TEACHER:result',
    'TEACHER:provenance',
    'TEACHER:regeneration-request',
    'TEACHER:regeneration-process',
    'TEACHER:regeneration-result',
    'COORDINATOR:request',
    'COORDINATOR:process',
    'COORDINATOR:status',
    'COORDINATOR:result',
    'COORDINATOR:provenance',
    'COORDINATOR:regeneration-request',
    'COORDINATOR:regeneration-process',
    'COORDINATOR:regeneration-result',
    'SCHOOL_ADMIN:request',
    'SCHOOL_ADMIN:process',
    'SCHOOL_ADMIN:status',
    'SCHOOL_ADMIN:result',
    'SCHOOL_ADMIN:provenance',
    'SCHOOL_ADMIN:regeneration-request',
    'SCHOOL_ADMIN:regeneration-process',
    'SCHOOL_ADMIN:regeneration-result',
  ],
  S: [
    'inactive-user',
    'inactive-membership',
    'inactive-organization',
    'platform-admin-membership',
    'missing-membership',
    'organization-mismatch',
  ].flatMap((state) => ['P1', 'P2', 'P3', 'P4'].map((operation) => `${state}:${operation}`)),
  L: ['PENDING', 'PROCESSING', 'SUCCEEDED', 'INSUFFICIENT_CONTEXT', 'FAILED'].flatMap((from) =>
    ['PENDING', 'PROCESSING', 'SUCCEEDED', 'INSUFFICIENT_CONTEXT', 'FAILED'].map(
      (to) => `${from}->${to}`,
    ),
  ),
  G: [
    'valid-draft',
    'valid-regeneration',
    'malformed',
    'schema-violation',
    'timeout',
    'rate-limit-retry',
    'transient-exhausted',
    'permanent-error',
    'budget-overrun',
    'replay',
  ],
  E1: [
    'no-result',
    'missing-review',
    'rejected-review',
    'same-timestamp-rejected-review',
    'missing-permission',
    'denied-permission',
    'expired-permission',
    'same-timestamp-denied-permission',
    'DRAFT',
    'SUSPENDED',
    'DEPRECATED',
    'FAILED',
    'NEEDS_RE_REVIEW',
    'wrong-curriculum-version',
    'wrong-node',
    'cross-tenant-private',
    'inactive-item',
  ],
  E2: [
    'rejected-review',
    'denied-permission',
    'expired-permission',
    'SUSPENDED',
    'DEPRECATED',
    'FAILED',
    'NEEDS_RE_REVIEW',
  ],
  O: [
    'valid-planned-draft',
    'unknown-field',
    'missing-section',
    'unplanned-key',
    'duplicate-key',
    'wrong-order',
    'type-mismatch',
    'difficulty-mismatch',
    'score-mismatch',
    'missing-citation',
    'unknown-citation',
    'foreign-citation',
  ],
  Q: [
    'target-only-replacement',
    'unrelated-structure-equal',
    'carried-forward-links',
    'generated-target-link',
    'missing-target',
    'foreign-target',
    'target-outside-base',
    'foreign-base',
    'idempotent-retry',
    'concurrent-sequential-revisions',
  ],
  C: [
    'duplicate-request',
    'active-lease',
    'stale-reclaim',
    'crash-after-claim',
    'crash-after-context',
    'terminal-replay',
    'concurrent-processing',
    'exactly-once-outcome',
  ],
  A: [
    'id-only-outbox',
    'safe-audit',
    'safe-worker-log',
    'safe-failure-class',
    'provider-redaction',
    'usage-append-only',
    'context-append-only',
    'source-link-append-only',
  ],
  D: [
    'run-identity',
    'context-update',
    'context-delete',
    'usage-update',
    'usage-delete',
    'source-link-update',
    'source-link-delete',
    'forged-context-item',
    'forged-context-lineage',
    'forged-question-run',
    'forged-source-link',
    'forged-owner',
    'terminal-reopen',
    'success-without-revision',
    'wrong-assessment-revision',
    'duplicate-idempotency',
    'duplicate-usage',
    'duplicate-context-order',
    'negative-usage',
    'orphan-identity',
  ],
} as const;
export const phase40AcceptanceCases = Object.entries(phase40AcceptanceRegistry).flatMap(
  ([matrix, ids]) => ids.map((id) => `${matrix}:${id}`),
);
export const phase40AcceptanceCount = phase40AcceptanceCases.length;
