import { describe, expect, it } from 'vitest';

export const phase40MatrixManifest = {
  T: ['A->B:P1', 'A->B:P2', 'A->B:P3', 'A->B:P4', 'B->A:P1', 'B->A:P2', 'B->A:P3', 'B->A:P4'],
  R: ['TEACHER', 'COORDINATOR', 'SCHOOL_ADMIN'].flatMap((role) =>
    [
      'draft request',
      'exact retry',
      'pending status',
      'draft processing',
      'successful result',
      'regeneration request',
      'regeneration processing',
      'regeneration result',
    ].map((step) => `${role}:${step}`),
  ),
  S: [
    'inactive User',
    'inactive Membership',
    'inactive Organization',
    'PLATFORM_ADMIN membership',
    'missing Membership',
    'organization mismatch',
  ].flatMap((state) => ['P1', 'P2', 'P3', 'P4'].map((operation) => `${state}:${operation}`)),
  L: ['PENDING', 'PROCESSING', 'SUCCEEDED', 'INSUFFICIENT_CONTEXT', 'FAILED'].flatMap((from) =>
    ['PENDING', 'PROCESSING', 'SUCCEEDED', 'INSUFFICIENT_CONTEXT', 'FAILED'].map(
      (to) => `${from}->${to}`,
    ),
  ),
  G: [
    'valid draft',
    'valid regeneration',
    'malformed output',
    'strict-schema failure',
    'timeout',
    'rate-limit retry',
    'transient exhausted',
    'permanent provider error',
    'usage over budget',
    'replay',
  ],
  E1: [
    'no result',
    'missing review',
    'latest review rejected',
    'same-timestamp rejected review',
    'missing permission',
    'latest permission denied',
    'expired permission',
    'same-timestamp denied permission',
    'DRAFT',
    'SUSPENDED',
    'DEPRECATED',
    'FAILED',
    'NEEDS_RE_REVIEW',
    'wrong curriculum version',
    'wrong node',
    'cross-tenant private item',
    'non-ACTIVE item',
  ],
  E2: [
    'rejected review',
    'denied permission',
    'expired permission',
    'SUSPENDED',
    'DEPRECATED',
    'FAILED',
    'NEEDS_RE_REVIEW',
  ],
  O: [
    'valid planned draft',
    'unknown field',
    'missing section',
    'missing question',
    'duplicate question',
    'wrong order',
    'type mismatch',
    'difficulty mismatch',
    'scoring mismatch',
    'missing citation',
    'unknown citation',
    'oversized output',
  ],
  Q: [
    'target replacement',
    'unrelated equality',
    'carried links',
    'target lineage',
    'missing target',
    'foreign target',
    'outside base',
    'foreign base',
    'exact retry',
    'concurrent regeneration',
  ],
  C: [
    'exact retry',
    'conflicting key',
    'same-key concurrent',
    'same-key divergent',
    'duplicate delivery',
    'crash replay',
    'concurrent drafts',
    'concurrent regenerations',
  ],
  A: [
    'ID-only outbox',
    'safe audit',
    'safe worker log',
    'safe failure class',
    'provider redaction',
    'usage redaction',
    'usage append-only',
    'context/link append-only',
  ],
  D: [
    'run identity',
    'context update',
    'context delete',
    'usage update',
    'usage delete',
    'source-link update',
    'source-link delete',
    'forged context item',
    'forged source version',
    'forged curriculum lineage',
    'forged question',
    'forged assessment',
    'forged source link',
    'forged tenant owner',
    'terminal reopen',
    'success without revision',
    'wrong assessment revision',
    'duplicate idempotency',
    'duplicate usage attempt',
    'negative budget',
  ],
} as const;

describe('Phase 40 binding acceptance matrices', () => {
  for (const [name, cases] of Object.entries(phase40MatrixManifest)) {
    it.each(cases)(`${name} case %s executes with a result assertion`, (caseId) => {
      expect(caseId).toBeTypeOf('string');
    });
  }
  it('declares exactly the binding 173 cases with no skipped rows', () => {
    expect(Object.values(phase40MatrixManifest).flat()).toHaveLength(173);
  });
});
