import { describe, expect, it } from 'vitest';
import { evaluateDeterministicRules, hasExactAnswerLeakage, normalizeValidationText, validationRules } from './validation.js';

const link = () => ({ questionId:'q1', revisionId:'r1', sourceVersionId:'sv1', knowledgeItemId:'ki1', locator:'paragraph:1', contentHash:'hash-1', sourceVersion:{id:'sv1'}, knowledgeItem:{id:'ki1'}, eligibility:{pedagogicalApproved:true,usageAllowed:true,sourceLifecycle:'ACTIVE',itemLifecycle:'ACTIVE',visibilityPermitted:true,exactPublishedCurriculum:true}, provenance:{generationRunId:'g1',generationRunState:'SUCCEEDED',operation:'DRAFT',assessmentId:'a1',curriculumVersionId:'cv1',outputRevisionId:'r1',promptTemplateVersion:'draft-v1',promptTemplateHash:'prompt-hash',modelConfigurationVersion:'fake-v1',modelConfigurationHash:'model-hash',responseSchemaVersion:'1.0.0',responseSchemaHash:'schema-hash',revisionId:'r1',questionId:'q1',sourceVersionId:'sv1',knowledgeItemId:'ki1'} });
export const snapshot = () => ({ id:'r1', generationRunId:'g1', generationOperation:'DRAFT' as const, promptTemplateVersion:'draft-v1', promptTemplateHash:'prompt-hash', modelConfigurationVersion:'fake-v1', modelConfigurationHash:'model-hash', responseSchemaVersion:'1.0.0', responseSchemaHash:'schema-hash', assessmentId:'a1', organizationId:'org1', ownerOrganizationId:'org1', state:'FINALIZED' as const, assessmentType:'WORKSHEET' as const, scoringMode:'NONE' as const, totalScoreUnits:null, curriculumVersion:{id:'cv1',status:'PUBLISHED' as const,nodeIds:['n1']}, curriculumNodeIds:['n1'], frozenPlan:{questions:[{key:'q1',order:0}]}, sections:[{key:'s1',order:0,scoreUnits:null,questions:[{id:'q1',key:'q1',prompt:'שאלה',instructions:'בחר',order:0,scoreUnits:null,answers:[{ownerType:'QUESTION',ownerId:'q1',text:'תשובה'}],rubrics:[],subQuestions:[],questionSourceLinks:[link()]}]}] });
const result = (value: unknown) => evaluateDeterministicRules(value);
const expectFails = (value: unknown, ids: string[]) => { const rows=result(value); expect(rows).toHaveLength(11); expect(rows.filter(r=>r.outcome==='FAIL').map(r=>r.ruleId)).toEqual(ids); for(const row of rows.filter(r=>r.outcome==='FAIL')) { expect(row.severity).toBe('BLOCKING'); expect(row.finding?.code).toBe(`${row.ruleId}_FAILED`); expect(row.messageKey).toBe(`${row.ruleId}_FAILED`); expect(Object.isFrozen(row.evidence)).toBe(true); } };
describe('Package 1B deterministic matrix',()=>{
  it('valid worksheet has eleven affirmative passes',()=>expect(result(snapshot()).every(r=>r.outcome==='PASS')).toBe(true));
  it('valid exact 10000 unit test has eleven affirmative passes',()=>{const s={...snapshot(),assessmentType:'TEST' as const,scoringMode:'POINTS' as const,totalScoreUnits:10000,sections:[{...snapshot().sections[0]!,scoreUnits:10000,questions:[{...snapshot().sections[0]!.questions[0]!,scoreUnits:10000}]}]};expect(result(s).every(r=>r.outcome==='PASS')).toBe(true);});
  it('malformed snapshot fails closed for every rule',()=>expectFails({},validationRules as unknown as string[]));
  it('missing ownership fails ownership only',()=>expectFails({...snapshot(),ownerOrganizationId:'other'},['REVISION_FINALIZED_AND_OWNED']));
  it('missing strict field fails closed at contract boundary',()=>{expectFails({...snapshot(),sections:[{...snapshot().sections[0]!,questions:[{...snapshot().sections[0]!.questions[0]!,prompt:undefined}]}]},validationRules as unknown as string[]);expectFails({...snapshot(),assessmentType:'ALIEN'},validationRules as unknown as string[]);expectFails({...snapshot(),scoringMode:'ALIEN'},validationRules as unknown as string[]);});
  it('frozen plan count mismatch fails plan only',()=>expectFails({...snapshot(),frozenPlan:{questions:[]}},['PLAN_COUNT_KEY_ORDER']));
  it('frozen plan key order mismatch fails plan only',()=>expectFails({...snapshot(),frozenPlan:{questions:[{key:'wrong',order:0}]}},['PLAN_COUNT_KEY_ORDER']));
  it('unpublished curriculum fails curriculum only',()=>expectFails({...snapshot(),curriculumVersion:{...snapshot().curriculumVersion,status:'DRAFT' as never}},['CURRICULUM_SCOPE_PUBLISHED']));
  it('unknown curriculum node fails curriculum only',()=>expectFails({...snapshot(),curriculumNodeIds:['unknown']},['CURRICULUM_SCOPE_PUBLISHED']));
  it('missing answer fails answer targets only',()=>expectFails({...snapshot(),sections:[{...snapshot().sections[0]!,questions:[{...snapshot().sections[0]!.questions[0]!,answers:[]}]}]},['ANSWER_COMPLETENESS_AND_TARGETS']));
  it('wrong answer owner fails answer targets only',()=>{expectFails({...snapshot(),sections:[{...snapshot().sections[0]!,questions:[{...snapshot().sections[0]!.questions[0]!,answers:[{ownerType:'SUBQUESTION',ownerId:'other',text:'תשובה'}]}]}]},['ANSWER_COMPLETENESS_AND_TARGETS']);expectFails({...snapshot(),sections:[{...snapshot().sections[0]!,questions:[{...snapshot().sections[0]!.questions[0]!,answers:[{text:'תשובה'}]}]}]},['ANSWER_COMPLETENESS_AND_TARGETS']);});
  it('score mismatch fails approved score rule only',()=>expectFails({...snapshot(),scoringMode:'POINTS' as const,assessmentType:'TEST' as const,totalScoreUnits:10},['EXACT_SCORE_TREE']));
  it('incomplete rubric allocation fails approved score rule only',()=>expectFails({...snapshot(),scoringMode:'POINTS' as const,assessmentType:'TEST' as const,totalScoreUnits:100,sections:[{...snapshot().sections[0]!,scoreUnits:100,questions:[{...snapshot().sections[0]!.questions[0]!,scoreUnits:100,rubrics:[{ownerType:'QUESTION',ownerId:'q1',scoreUnits:50}]}]}]},['EXACT_SCORE_TREE']));
  it('duplicate stable ID fails identity only',()=>expectFails({...snapshot(),sections:[{...snapshot().sections[0]!,questions:[snapshot().sections[0]!.questions[0]!,{...snapshot().sections[0]!.questions[0]!,key:'q2',order:1,prompt:'אחר',answers:[{ownerType:'QUESTION',ownerId:'q1',text:'תגובה'}],questionSourceLinks:[link()]}]}],frozenPlan:{questions:[{key:'q1',order:0},{key:'q2',order:1}]}},['STABLE_ID_AND_EXACT_DUPLICATE']));
  it('normalized duplicate text fails identity only',()=>expectFails({...snapshot(),sections:[{...snapshot().sections[0]!,questions:[snapshot().sections[0]!.questions[0]!,{...snapshot().sections[0]!.questions[0]!,id:'q2',key:'q2',order:1,prompt:'  שאלה  ',answers:[{ownerType:'QUESTION',ownerId:'q2',text:'תגובה'}],questionSourceLinks:[{...link(),questionId:'q2',provenance:{...link().provenance,questionId:'q2'}}]}]}],frozenPlan:{questions:[{key:'q1',order:0},{key:'q2',order:1}]}},['STABLE_ID_AND_EXACT_DUPLICATE']));
  it('near match remains distinct',()=>expect(result({...snapshot(),sections:[{...snapshot().sections[0]!,questions:[snapshot().sections[0]!.questions[0]!,{...snapshot().sections[0]!.questions[0]!,id:'q2',key:'q2',order:1,prompt:'שאלות',answers:[{ownerType:'QUESTION',ownerId:'q2',text:'תגובה'}],questionSourceLinks:[{...link(),questionId:'q2',provenance:{...link().provenance,questionId:'q2'}}]}]}],frozenPlan:{questions:[{key:'q1',order:0},{key:'q2',order:1}]}}).filter(r=>r.outcome==='FAIL')).toHaveLength(0));
  it('exact normalized answer leakage fails leakage only',()=>{expectFails({...snapshot(),sections:[{...snapshot().sections[0]!,questions:[{...snapshot().sections[0]!.questions[0]!,prompt:'שאלה ארוכה',answers:[{ownerType:'QUESTION',ownerId:'q1',text:'שאלה'}]}]}]},['DETERMINISTIC_ANSWER_LEAKAGE']);expect(hasExactAnswerLeakage('שאלה נכונה','שאלה נכונות')).toBe(false);});
  it('missing source identity fails source, eligibility and provenance',()=>{const base=snapshot();expectFails({...base,sections:[{...base.sections[0]!,questions:[{...base.sections[0]!.questions[0]!,questionSourceLinks:[]}]}]},['SOURCE_LINK_COMPLETENESS_AND_IDENTITY','CURRENT_SOURCE_ELIGIBILITY','GENERATION_REVISION_PROVENANCE']);for(const change of [{knowledgeItem:{id:'foreign'}},{sourceVersion:{id:'foreign'}},{locator:''},{contentHash:''}])expectFails({...base,sections:[{...base.sections[0]!,questions:[{...base.sections[0]!.questions[0]!,questionSourceLinks:[{...link(),...change}]}]}]},validationRules as unknown as string[]);});
  it('revoked current eligibility fails eligibility only',()=>{const base=snapshot();const denied=[{pedagogicalApproved:false},{usageAllowed:false},{sourceLifecycle:'SUSPENDED'},{itemLifecycle:'SUSPENDED'},{visibilityPermitted:false},{exactPublishedCurriculum:false}];for(const change of denied)expectFails({...base,sections:[{...base.sections[0]!,questions:[{...base.sections[0]!.questions[0]!,questionSourceLinks:[{...link(),eligibility:{...link().eligibility,...change}}]}]}]},['CURRENT_SOURCE_ELIGIBILITY']);expect(result(base).find(r=>r.ruleId==='CURRENT_SOURCE_ELIGIBILITY')?.outcome).toBe('PASS');});
  it('generation revision lineage mismatch fails provenance only',()=>{const base=snapshot();const mutate=(p:Record<string,unknown>)=>expectFails({...base,sections:[{...base.sections[0]!,questions:[{...base.sections[0]!.questions[0]!,questionSourceLinks:[{...link(),provenance:{...link().provenance,...p}}]}]}]},['GENERATION_REVISION_PROVENANCE']);mutate({generationRunId:'other'});mutate({outputRevisionId:'other'});mutate({promptTemplateHash:'other'});mutate({modelConfigurationHash:'other'});mutate({responseSchemaHash:'other'});mutate({questionId:'other'});mutate({knowledgeItemId:'other'});expectFails({...base,sections:[{...base.sections[0]!,questions:[{...base.sections[0]!.questions[0]!,questionSourceLinks:[{...link(),provenance:{generationRunState:'SUCCEEDED',outputRevisionId:'r1',revisionId:'r1',questionId:'q1'}}]}]}]},validationRules as unknown as string[]);});
});
